version: '3'
services:
  app:
    build: .
    image: ayotundepaul/devops-practical:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

